version: '3'

networks:
  lednet:
#    name: infra_led
    driver: bridge
    
services:
  web:
    build: ./nginx
    image: nginx_led
    container_name: nginx-led-container
    restart: always
    depends_on:
      - test_lab
      - led_flask
    networks:
      - lednet
    ports:
        - 80:80
  led_flask:
    build: ./backend
    image: backend_led
    container_name: backend-led-container
    restart: always
    networks:
      - lednet
    user: root
    privileged: true
  test_lab:
    build: ./
    networks:
      - lednet
    image: test_lab
    restart: always
#     ports:
#       - 8888:8888
    volumes:
      - ./notebook:/notebook
      - /sys:/sys
    devices:
      - /dev/gpiomem:/dev/gpiomem
        #- /dev/mem:/dev/mem
    user: root
    privileged: true
