version: '3'

services:
  test_lab:
    build: ./
    image: test_lab
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./notebook:/notebook
      - /sys:/sys
    devices:
      - /dev/gpiomem:/dev/gpiomem
        #- /dev/mem:/dev/mem
    user: root
    privileged: true
